command=/usr/share/i3blocks/$BLOCK_NAME

separator_block_width=12
markup=none

# ============================================================
# Night Owl
# ============================================================

color=#CBE0F0


# ============================================================
# Network
# ============================================================

[network]
command=/home/johan/.config/i3/network
interval=5
separator=true

# ============================================================
# Volume
# ============================================================

[volume]
command=/home/johan/.config/i3/volume
interval=1
signal=10
separator=true

# ============================================================
# Disk
# ============================================================

[disk]
label=⌂
interval=30
separator=true


# ============================================================
# CPU
# ============================================================

[cpu_usage]
label=CPU
interval=10
min_width=CPU: 100.00%
separator=true


# ============================================================
# Battery
# ============================================================

[battery]
label=⚡
interval=30
separator=true


# ============================================================
# Time
# ============================================================

[time]
command=date '+%a %d %b  %H:%M'
interval=1
